### ISSUE TITLE
Better support for zero-entry trees

### ISSUE THREAD

**Issue by ponyisi** [scikit-hep/uproot#109]
Hi,

I am enjoying trying out uproot.  In trying to look at the dask support, I ran into the following when trying to read a file with an empty tree (one can of course get these occasionally when running on the output of skim jobs):

```
>>> t.numentries
0
>>> t.lazyarrays(branches=['RunNumber', 'EventNumber'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/eos/user/p/ponyisi/.local/lib/python2.7/site-packages/uproot/tree.py", line 514, in lazyarrays
    lazyarrays = [(branch.name, branch.lazyarray(interpretation=interpretation, limitbytes=limitbytes, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor)) for branch, interpretation in branches]
  File "/eos/user/p/ponyisi/.local/lib/python2.7/site-packages/uproot/tree.py", line 1427, in lazyarray
    return LazyArray._frombranch(self, interpretation, cache, basketcache, keycache, executor)
  File "/eos/user/p/ponyisi/.local/lib/python2.7/site-packages/uproot/tree.py", line 1742, in _frombranch
    self._chunksize = max(onlybranch.basket_numentries(i) for i in range(onlybranch.numbaskets))
ValueError: max() arg is an empty sequence
>>>
```
As far as I can tell, replacing the expression by "max() if onlybranch.numbaskets > 0 else 0" makes things work.

Best,
Peter

**Comment by jpivarski** [comment]
You get revision 100!
