### ISSUE TITLE
Attempted basket-recovery fails

### ISSUE THREAD

**Issue by reikdas** [scikit-hep/uproot#126]
```
>>> import uproot
>>> file = uproot.open("Test1.root")
>>> file["ChannelSet"].show()
PSR_ph                     TStreamerInfo              asgenobj(TXboxDAQChannel)  #Truncated 
>>> file["ChannelSet"]["PSR_ph"]
<TBranchElement b'PSR_ph' at 0x769280b26d30>

>>> file["ChannelSet"].array("PSR_ph")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chronos/user/Downloads/uproot/uproot/tree.py", line 408, in array
    return self.get(branch).array(interpretation=interpretation, entrystart=entrystart, entrystop=entrystop, flatten=flatten, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=blocking)
  File "/home/chronos/user/Downloads/uproot/uproot/tree.py", line 1253, in array
    self._tryrecover()
  File "/home/chronos/user/Downloads/uproot/uproot/tree.py", line 1548, in _tryrecover
    self._recover()
  File "/home/chronos/user/Downloads/uproot/uproot/tree.py", line 1544, in _recover
    raise ValueError("entries in recovered baskets (offsets {0}) don't add up to total number of entries ({1})".format(entryoffsets, self.numentries))
ValueError: entries in recovered baskets (offsets [0]) don't add up to total number of entries (3)

>>> file["ChannelSet"]["PSR_ph"].basket(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chronos/user/Downloads/uproot/uproot/tree.py", line 1117, in basket
    self._tryrecover()
  File "/home/chronos/user/Downloads/uproot/uproot/tree.py", line 1548, in _tryrecover
    self._recover()
  File "/home/chronos/user/Downloads/uproot/uproot/tree.py", line 1544, in _recover
    raise ValueError("entries in recovered baskets (offsets {0}) don't add up to total number of entries ({1})".format(entryoffsets, self.numentries))
ValueError: entries in recovered baskets (offsets [0]) don't add up to total number of entries (3)
```

2 Test files attached 

[tests.zip](https://github.com/scikit-hep/uproot/files/2374636/tests.zip)

**Comment by jpivarski** [comment]
This is not supposed to be a readable branch. It's more of a "structural" branch; it exists to specify that all the subbranches under it were parts of a split class, but it doesn't, in itself, have any data.

The error message is misleading. We should be emitting an error message complaining about trying to read a branch with no interpretation (the `.interpretation` field of this branch is `None`), not recovery. The heuristic that a branch needs to be recovered if its number of entries is not equal to the sum of its baskets is flawed, or at least it has to happen _after_ the check for a lacking interpretation.
