### ISSUE TITLE
ValueError maximum stop instead of StopIteration

### ISSUE THREAD

**Issue by vkuznet** [scikit-hep/uproot#146]
Jim,
I'm experience a weird error with uproot using its new version 3.1.1 which does not exist in version 2.5.12. Here is a snippet of code I'm doing (I placed ROOT file to AFS for your convenience):
```
import uproot
fin='/afs/cern.ch/user/v/valya/public/nano-RelValTTBar.root'
nevts=1000
branch='Events'
cache={}
istream = uproot.open(fin)
tree = istream[branch]
gen = tree.iterate(entrysteps=nevts, keycache=cache)
for idx in range(10):
    print("read {}th chunk of {} events".format(idx+1, nevts))
    branches = next(gen)
```
and here is an error I'm getting using uproot 3.1.1
```
read 1th chunk of 1000 events
read 2th chunk of 1000 events
Traceback (most recent call last):
  File "ttt.py", line 11, in <module>
    branches = next(gen)
  File "/data/vk/anaconda3/lib/python3.6/site-packages/uproot/tree.py", line 629, in iterate
    future = branch._step_array(interpretation, basket_itemoffset, basket_entryoffset, start, stop, basketcache, keycache, executor, explicit_basketcache)
  File "/data/vk/anaconda3/lib/python3.6/site-packages/uproot/tree.py", line 1428, in _step_array
    _delayedraise(fill(j))
  File "/data/vk/anaconda3/lib/python3.6/site-packages/uproot/tree.py", line 98, in _delayedraise
    raise err.with_traceback(trc)
  File "/data/vk/anaconda3/lib/python3.6/site-packages/uproot/tree.py", line 1421, in fill
    basket_entryoffset[j + 1])
  File "/data/vk/anaconda3/lib/python3.6/site-packages/uproot/interp/jagged.py", line 144, in fill
    destination.counts[entrystart:entrystop] = source.counts
  File "/data/vk/anaconda3/lib/python3.6/site-packages/awkward/array/jagged.py", line 280, in counts
    self._valid()
  File "/data/vk/anaconda3/lib/python3.6/site-packages/awkward/array/jagged.py", line 381, in _valid
    raise ValueError("maximum stop ({0}) is beyond the length of the content ({1})".format(self._stops.reshape(-1).max(), len(self._content)))
ValueError: maximum stop (2149) is beyond the length of the content (1094)
```
But using uproot 2.5.12 I process correctly 9K events in this file:
```
read 1th chunk of 1000 events
read 2th chunk of 1000 events
read 3th chunk of 1000 events
read 4th chunk of 1000 events
read 5th chunk of 1000 events
read 6th chunk of 1000 events
read 7th chunk of 1000 events
read 8th chunk of 1000 events
read 9th chunk of 1000 events
read 10th chunk of 1000 events
Traceback (most recent call last):
  File "ttt.py", line 11, in <module>
    branches = next(gen)
StopIteration
```
And, I got StopIteration from generator as expected.

**Comment by jpivarski** [comment]
That was scary but it turned out to be a minor thing.

The new `JaggedArray` has a `.counts` property that does sanity checks on the values in `starts` and `stops` that make sense for a user's finalized jagged array but not for the interior of a filling process. Specifically, the `offsets` are relative to the beginning of the basket but in an `iterate` you might be starting after the beginning of the basket. Only differences (`counts`) are meaningful, so I build up the array by collecting

```python
destination.counts[entrystart:entrystop] = source.counts
```

However, the sanity-check gets triggered in the property, so I needed to change this line to

```python
destination.counts[entrystart:entrystop] = source.stops - source.starts    # no check
```

This correction is on its way; it will be uproot 3.1.2.
