### ISSUE TITLE
uproot 3.4.17 not opening ROOT files (but 3.4.4 does)

### ISSUE THREAD

**Issue by sdporzio** [scikit-hep/uproot#267]
Opening ROOT files with `ROOTDirectory.pandas.df()` fails in 3.4.17, but works fine when downgrading to 3.3.4:

Traceback
```
Traceback (most recent call last):
  File "/pc2013-data2/sdporzio/Anaconda3/envs/ana/lib/python3.7/site-packages/uproot/interp/auto.py", line 248, in interpret
    fromdtype = _leaf2dtype(branch._fLeaves[0], awkward).newbyteorder(">")
  File "/pc2013-data2/sdporzio/Anaconda3/envs/ana/lib/python3.7/site-packages/uproot/interp/auto.py", line 121, in _leaf2dtype
    return _ftype2dtype(leaf._fType, awkward)
  File "/pc2013-data2/sdporzio/Anaconda3/envs/ana/lib/python3.7/site-packages/uproot/interp/auto.py", line 90, in _ftype2dtype
    raise _NotNumerical
uproot.interp.auto._NotNumerical


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "rootToHDF5.py", line 28, in <module>
    dfEv = aux.Root2Pandas(inFile,'HelephantFinder/EventData')
  File "/pc2013-data3/sdporzio/SterileNeutrinoAnalysisFramework/0_DataPreparation/Functions/aux.py", line 21, in Root2Pandas
    df = rTree.pandas.df(["*"],flatten=False,namedecode='utf-8')
  File "/pc2013-data2/sdporzio/Anaconda3/envs/ana/lib/python3.7/site-packages/uproot/_connect/to_pandas.py", line 56, in df
    return self._tree.arrays(branches=branches, outputtype=pandas.DataFrame, namedecode=namedecode, entrystart=entrystart, entrystop=entrystop, flatten=flatten, flatname=flatname, awkwardlib=awkwardlib, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=blocking)
  File "/pc2013-data2/sdporzio/Anaconda3/envs/ana/lib/python3.7/site-packages/uproot/tree.py", line 469, in arrays
    branches = list(self._normalize_branches(branches, awkward))
  File "/pc2013-data2/sdporzio/Anaconda3/envs/ana/lib/python3.7/site-packages/uproot/tree.py", line 760, in _normalize_branches
    interpretation = interpret(branch, awkward)
  File "/pc2013-data2/sdporzio/Anaconda3/envs/ana/lib/python3.7/site-packages/uproot/interp/auto.py", line 341, in interpret
    fromdtype = _ftype2dtype(branch._streamer._fCtype, awkward)
  File "/pc2013-data2/sdporzio/Anaconda3/envs/ana/lib/python3.7/site-packages/uproot/interp/auto.py", line 62, in _ftype2dtype
    fType = _normalize_ftype(fType)
  File "/pc2013-data2/sdporzio/Anaconda3/envs/ana/lib/python3.7/site-packages/uproot/interp/auto.py", line 56, in _normalize_ftype
    if uproot.const.kOffsetL < fType < uproot.const.kOffsetP:
TypeError: '<' not supported between instances of 'int' and 'NoneType'

```

**Comment by jpivarski** [comment]
This `uproot.const.kOffsetL < fType < uproot.const.kOffsetP` was added between versions 3.3.4 and 3.4.17, and it looks like it just doesn't handle the `fType is None` case. I didn't know that some ROOT files might have `std::vector` streamers with `fCtype is None`, but presumably that wouldn't be a numerical type.

I've

**Comment by sdporzio** [comment]
Sorry for the belated answer. The fix seems to have solved the issue!

**Comment by jpivarski** [comment]
Deploying this now; sorry for the delay.
