### ISSUE TITLE
uproot.iterate does not like multiple files

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/uproot#274]
The following code snippet works perfectly:

```python
for fname in args.files:
    with uproot.open(fname) as f:
        tree = f[args.treename]
        for start, stop, events in tree.iterate(branches, reportentries=True):
            pass
```

the following code snippet fails

```python
for start, stop, events in uproot.iterate(
    args.files, args.treename, branches, reportentries=True
):
    pass
```

with this error:

```
Traceback (most recent call last):
  File "lund2hdf5.py", line 101, in <module>
    args.files, args.treename, branches, reportentries=True
  File "/usr/local/lib/python3.7/site-packages/uproot/tree.py", line 89, in iterate
    for tree, newbranches, globalentrystart, thispath, thisfile in _iterate(path, treepath, branches, awkward, localsource, xrootdsource, httpsource, **options):
  File "/usr/local/lib/python3.7/site-packages/uproot/tree.py", line 150, in _iterate
    elif not newbranches[key].compatible(oldbranches[key]):
  File "/usr/local/lib/python3.7/site-packages/uproot/interp/objects.py", line 306, in compatible
    return isinstance(other, asgenobj) and self.cls.__name__ == other.cls.__name__
AttributeError: 'asgenobj' object has no attribute 'cls'
```

**Comment by jpivarski** [comment]
See PR #275.
