### ISSUE TITLE
LazyArray loading of `std::vector<>` branch fails with 'value too large' error

### ISSUE THREAD

**Issue by chenel** [scikit-hep/uproot#317]
Hi,

I've been experimenting with Uproot and thought I'd give it a try on a set of flat ROOT ntuples I need to make some plots from.  These guys contain a single `TTree` called `gst` which has a large, but not unreasonable number of branches (93).  Many of the branches are `std::vector<double>` or `std::vector<int>`.

I can read these vector-of-value branches fine when I open one file at a time with `uproot.open()`, pull the tree out, and use `array()` or `arrays()`, e.g.:
```
>>> f = uproot.open("/path/to/gst.root")
>>> gst = f["gst"]
>>> pdgf = gst.array("pdgf")
>>> pdgf[0]
array([2112, 2212,  211, 2212,  211], dtype=int32)
```
which is an array of pdg codes as expected.

However, when I try to use a `lazyarray()` to chain several ntuples of with the same tree in them together, I get a (rather inscrutable) `value too large` error:
```
>>> uproot.lazyarray("/path/to/*.gst.root", "gst", "pdgf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/awkward/array/base.py", line 106, in __repr__
    return "<{0} {1} at 0x{2:012x}>".format(self.__class__.__name__, str(self), id(self))
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/awkward/array/chunked.py", line 272, in __str__
    return super(ChunkedArray, self).__str__()
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/awkward/array/base.py", line 96, in __str__
    first = self[:3]
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/awkward/array/chunked.py", line 411, in __getitem__
    chunk = self._chunks[chunkid][(slice(local_start, local_stop, step),)]
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/awkward/array/virtual.py", line 369, in __getitem__
    return self.array[where]
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/awkward/array/chunked.py", line 411, in __getitem__
    chunk = self._chunks[chunkid][(slice(local_start, local_stop, step),)]
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/awkward/array/virtual.py", line 369, in __getitem__
    return self.array[where]
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/awkward/array/virtual.py", line 295, in array
    return self.materialize()
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/awkward/array/virtual.py", line 326, in materialize
    array = self._util_toarray(self._generator(*self._args, **self._kwargs), self.DEFAULTTYPE)
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/uproot/tree.py", line 1912, in __call__
    return self.branch.array(interpretation=self.interpretation, entrystart=entrystart, entrystop=entrystop, flatten=self.flatten, awkwardlib=self.awkwardlib, cache=None, basketcache=self.basketcache, keycache=self.keycache, executor=self.executor, blocking=True)
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/uproot/tree.py", line 1395, in array
    _delayedraise(fill(j))
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/uproot/tree.py", line 56, in _delayedraise
    exec("raise cls, err, trc")
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/uproot/tree.py", line 1363, in fill
    source = self._basket(i, interpretation, local_entrystart, local_entrystop, awkward, basketcache, keycache)
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/uproot/tree.py", line 1149, in _basket
    basketcache[basketcachekey] = basketdata
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/uproot/cache.py", line 67, in __setitem__
    self._cache[where] = what
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/cachetools/lru.py", line 21, in __setitem__
    cache_setitem(self, key, value)
  File "/cluster/tufts/minos/external-update/install/lib/python2.7/site-packages/cachetools/cache.py", line 49, in __setitem__
    raise ValueError('value too large')
ValueError: value too large
```
I experimented with this with a cache (per the example) with sizes up to 1 GB with no different results.  (The files are only 53MB each so it seems unlikely that I'd need to go much bigger than that.)

Intriguingly, if I try to access a branch that contains only a single value, it works fine:
```
>>> uproot.lazyarray("/path/to/*.gst.root", "gst", "neu")
<ChunkedArray [14 14 14 ... 14 14 14] at 0x000002ba0350>
```
so something has gone wrong with the 'ragged' array stuff, I suppose.

Would appreciate any help here -- Uproot seems like a nice tool.  Thanks!

**Comment by jpivarski** [comment]
I suspect that the issue is related to how `ChunkedArrays` and `VirtualArrays` (which are used together to build lazy arrays) report their `nbytes`. If so, it would be an awkward-array error, not an uproot error, but the demarcation line isn't made clear by the interface.

`ArrayCache` uses its values' `nbytes` to determine if it's too full and needs to evict some data to stay under its `limitbytes`. However, if a single item is larger than its limit, then no amount of eviction will help. The `cachetools` library says, "value too large" when this happens.

The values in question are supposed to be _chunks_, not the entire array, so a 1 GB limit means that no _chunk_ can be larger than 1 GB. Since your largest file is 53 MB, it sounds like this shouldn't be happening: chunks can be smaller than files, but files aren't glued together into larger chunks. Nevertheless, you do have another handle: you can make the chunks smaller with `entrysteps` (determines how many entries are in a chunk).

If it's counting the entire array as one object in the cache (thus, the sum of all chunks is what counts against you), then that would be a bug. I took a look at how `VirtualArray` handles `nbytes`, since it in principle doesn't know the size of its data until it loads it, and it takes `nbytes` as an optional constructor argument. Uproot has to give it the right value (and uproot has enough information to do so: ROOT files let you know the uncompressed size of a TBasket before you read it)—maybe that's where the bug is.

In the short term, you might want to look into iterating over your data with the older (and better tested) [uproot.iterate](https://uproot.readthedocs.io/en/latest/opening-files.html#uproot-iterate) function (see also the [tutorial](https://github.com/scikit-hep/uproot#iteration)). Some users have told me they prefer getting data a chunk at a time in a for loop (what `uproot.iterate` does) because it gives them more control over the memory management.

Good luck!

**Comment by chenel** [comment]
Indeed, I do seem to be able to do what I want (so far, at least) using `uproot.iterate`.  It's a little less convenient for my purposes, but it's functional.  I'm not sure whether I need to propagate any of this upstream, if it's really a problem with awkward-array?  Or does it need more triage still?

**Comment by jpivarski** [comment]
I need to more fully triage it, and then fix it. (It does sound like a bug, but there's still a chance that it's a misunderstanding, depending on the size of your files, but you've told me that the biggest is 53 MB.)

Thanks for letting me know!

(I wanted to give you another option so that you're not held up by the time it takes me to fix it.)

**Comment by chenel** [comment]
Oh, ok -- thanks!

I'd be happy to provide one (or several) of the files if you find you can't reproduce it with something simpler -- just let me know.

Appreciate the lightning-fast responses!

**Comment by jpivarski** [comment]
I haven't been able to reproduce it. If you have an example for me to get working, please re-open this issue with that example.

(I'm going through a lot of issues now and need to close ones I can't fix without more information.)

**Comment by chenel** [comment]
Ok.  I'll supply an example when I have a moment.
