### ISSUE TITLE
Handle TH1 w/ labeled bins

### ISSUE THREAD

**Issue by kpedro88** [scikit-hep/uproot#33]
Currently I get this trace if I try to access one:
```
>>> h = f["cutflow"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/uscms/home/pedrok/.local/lib/python2.7/site-packages/uproot/rootio.py", line 199, in __getitem__
    return self.get(name)
  File "/uscms/home/pedrok/.local/lib/python2.7/site-packages/uproot/rootio.py", line 314, in get
    return key.get()
  File "/uscms/home/pedrok/.local/lib/python2.7/site-packages/uproot/rootio.py", line 797, in get
    return self._context.classes[classname].read(self._source, self._cursor.copied(), self._context)
  File "/uscms/home/pedrok/.local/lib/python2.7/site-packages/uproot/rootio.py", line 738, in read
    out = cls._readinto(out, source, cursor, context)
  File "<generated from TStreamerInfo 'TH1F' at 0x7f387398d990>", line 10, in _readinto
  File "<generated from TStreamerInfo 'TH1' at 0x7f387398da10>", line 15, in _readinto
  File "/uscms/home/pedrok/.local/lib/python2.7/site-packages/uproot/rootio.py", line 738, in read
    out = cls._readinto(out, source, cursor, context)
  File "<generated from TStreamerInfo 'TAxis' at 0x7f387398db10>", line 16, in _readinto
  File "/uscms/home/pedrok/.local/lib/python2.7/site-packages/uproot/rootio.py", line 421, in _readobjany
    obj = fct.read(source, cursor, context)        # new object
  File "/uscms/home/pedrok/.local/lib/python2.7/site-packages/uproot/rootio.py", line 738, in read
    out = cls._readinto(out, source, cursor, context)
  File "<generated from TStreamerInfo 'THashList' at 0x7f3882536cd0>", line 9, in _readinto
ValueError: attempting to read THashList object version 5 with a class generated by streamer version 0
```
Can provide example file on request.

**Comment by jpivarski** [comment]
I don't have an example of this, so it would be helpful to see it. (I've learned that you can drag-and-drop into these issues to attach files.)

Moreover, this stack trace doesn't look like a benign unimplemented error. A different version of the class was found in the file than was defined in the class, which really shouldn't happen. It could be that I've been naive and multiple versions of a class can exist in the same file, in which case I'll need to change my dict from {name → class} to {name → {version → class}} or something. I'd like to see exactly the file you used to produce this error, to see what kinds of streamers it has.

Thanks!

**Comment by kpedro88** [comment]
Here's a ROOT file with just the labeled-bin histogram that causes this error when I try to open it:
https://www.dropbox.com/s/v9xf202l6i50oiy/test.root?dl=0
```
f = up.open("test.root")
h = f["cutflow"]
```

**Comment by jpivarski** [comment]
Okay; it wasn't anything drastic. As it turns out, THashList is one of the dozen or so classes that are so fundamental they are exceptions to the streamer pattern. (It probably predated automatic streamers, and they had to put in exceptions to be able to read pre-streamer files.)

Would you mind if I include this file in the test suite as issue-33.root?

**Comment by kpedro88** [comment]
Sure, since it just has the one histogram it's fine to include it as an example.

**Comment by jpivarski** [comment]
```
>>> h.show()
                           0                                               41529
                           +---------------------------------------------------+
(underflow)          0     |                                                   |
Dijet                39551 |*************************************************  |
MET                  27951 |**********************************                 |
MuonVeto             27911 |**********************************                 |
IsoMuonTrackVeto     27861 |**********************************                 |
ElectronVeto         27737 |**********************************                 |
IsoElectronTrackVeto 27460 |**********************************                 |
IsoPionTrackVeto     26751 |*********************************                  |
(overflow)           0     |                                                   |
                           +---------------------------------------------------+
```

**Comment by jpivarski** [comment]
It has a test and it will be release 2.5.10 in GitHub and PyPI. You can access the labels via `TH1.xlabel`.

Thanks for letting me use the file!
