### ISSUE TITLE
Unable to open GEN-SIM-DIGI-RAW file

### ISSUE THREAD

**Issue by vkuznet** [scikit-hep/uproot#35]
With uproot 2.1.5 version I'm unable to open GEN-SIM-DIGI-RAW file
(/store/relval/CMSSW_9_4_0/RelValTTbar_13/GEN-SIM-DIGI-RAW/PU25ns_94X_upgrade2018_realistic_v5-v1/10000/3245F8B2-CBC8-E711-8FCA-0CC47A4D762E.root). Here is traceback, it fails in uproot.open.

```
Traceback (most recent call last):
  File "./tfaas.py", line 53, in listBranches
    with uproot.open(fin) as tree:
  File "/afs/cern.ch/work/v/valya/uproot-2.1.5/uproot/rootio.py", line 59, in open
    return ROOTDirectory.read(localsource(path), **options)
  File "/afs/cern.ch/work/v/valya/uproot-2.1.5/uproot/rootio.py", line 132, in read
    streamerinfos, streamerinfosmap, streamerrules = _readstreamers(streamerkey._source, streamerkey._cursor, streamercontext)
  File "/afs/cern.ch/work/v/valya/uproot-2.1.5/uproot/rootio.py", line 453, in _readstreamers
    streamerinfos = list(topological_sort(streamerinfos))
  File "/afs/cern.ch/work/v/valya/uproot-2.1.5/uproot/rootio.py", line 449, in topological_sort
    raise ValueError("cannot sort TStreamerInfos into dependency order:\n\n{0}".format("\n".join("{0:20s} requires {1}".format(item.fName, " ".join(dependencies)) for item, dependencies in items)))
ValueError: cannot sort TStreamerInfos into dependency order:

SiPixelRecHit        requires TrackerSingleRecHit
TrackerSingleRecHit  requires OmniClusterRef BaseTrackerRecHit
OmniClusterRef       requires edm::RefCoreWithIndex
SiStripMatchedRecHit2D requires OmniClusterRef BaseTrackerRecHit
SiStripRecHit2D      requires TrackerSingleRecHit
ProjectedSiStripRecHit2D requires TrackerSingleRecHit
L2MuonTrajectorySeed requires edm::Ref<vector<l1extra::L1MuonParticle>,l1extra::L1MuonParticle,edm::refhelper::FindUsingAdvance<vector<l1extra::L1MuonParticle>,l1extra::L1MuonParticle> > TrajectorySeed edm::Ref<BXVector<l1t::Muon>,l1t::Muon,edm::refhelper::FindUsingAdvance<BXVector<l1t::Muon>,l1t::Muon> >
L3MuonTrajectorySeed requires edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> > edm::Ref<vector<l1extra::L1MuonParticle>,l1extra::L1MuonParticle,edm::refhelper::FindUsingAdvance<vector<l1extra::L1MuonParticle>,l1extra::L1MuonParticle> > TrajectorySeed edm::Ref<BXVector<l1t::Muon>,l1t::Muon,edm::refhelper::FindUsingAdvance<BXVector<l1t::Muon>,l1t::Muon> >
TrackingParticle     requires edm::RefVector<vector<reco::GenParticle>,reco::GenParticle,edm::refhelper::FindUsingAdvance<vector<reco::GenParticle>,reco::GenParticle> > edm::RefVector<vector<TrackingVertex>,TrackingVertex,edm::refhelper::FindUsingAdvance<vector<TrackingVertex>,TrackingVertex> > edm::Ref<vector<TrackingVertex>,TrackingVertex,edm::refhelper::FindUsingAdvance<vector<TrackingVertex>,TrackingVertex> >
edm::Ref<vector<TrackingVertex>,TrackingVertex,edm::refhelper::FindUsingAdvance<vector<TrackingVertex>,TrackingVertex> > requires edm::RefCoreWithIndex
reco::Electron       requires reco::RecoCandidate edm::Ref<vector<reco::GsfTrack>,reco::GsfTrack,edm::refhelper::FindUsingAdvance<vector<reco::GsfTrack>,reco::GsfTrack> > edm::Ref<vector<reco::SuperCluster>,reco::SuperCluster,edm::refhelper::FindUsingAdvance<vector<reco::SuperCluster>,reco::SuperCluster> > edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> >
reco::GsfTrack       requires ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<Double32_t>,ROOT::Math::DefaultCoordinateSystemTag> reco::Track edm::Ref<vector<reco::GsfTrackExtra>,reco::GsfTrackExtra,edm::refhelper::FindUsingAdvance<vector<reco::GsfTrackExtra>,reco::GsfTrackExtra> >
reco::Track          requires reco::TrackBase edm::Ref<vector<reco::TrackExtra>,reco::TrackExtra,edm::refhelper::FindUsingAdvance<vector<reco::TrackExtra>,reco::TrackExtra> >
reco::IsolatedPixelTrackCandidate requires reco::RecoCandidate edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> > edm::Ref<BXVector<l1t::Tau>,l1t::Tau,edm::refhelper::FindUsingAdvance<BXVector<l1t::Tau>,l1t::Tau> > edm::Ref<vector<l1extra::L1JetParticle>,l1extra::L1JetParticle,edm::refhelper::FindUsingAdvance<vector<l1extra::L1JetParticle>,l1extra::L1JetParticle> >
edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> > requires edm::RefCoreWithIndex
edm::Ref<vector<l1extra::L1JetParticle>,l1extra::L1JetParticle,edm::refhelper::FindUsingAdvance<vector<l1extra::L1JetParticle>,l1extra::L1JetParticle> > requires edm::RefCoreWithIndex
reco::MuonTrackLinks requires edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> >
reco::PFTau          requires edm::RefVector<vector<reco::PFRecoTauChargedHadron>,reco::PFRecoTauChargedHadron,edm::refhelper::FindUsingAdvance<vector<reco::PFRecoTauChargedHadron>,reco::PFRecoTauChargedHadron> > edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> > edm::RefVector<vector<reco::RecoTauPiZero>,reco::RecoTauPiZero,edm::refhelper::FindUsingAdvance<vector<reco::RecoTauPiZero>,reco::RecoTauPiZero> > edm::Ref<vector<reco::PFTauTagInfo>,reco::PFTauTagInfo,edm::refhelper::FindUsingAdvance<vector<reco::PFTauTagInfo>,reco::PFTauTagInfo> > reco::BaseTau edm::Ref<vector<reco::PFJet>,reco::PFJet,edm::refhelper::FindUsingAdvance<vector<reco::PFJet>,reco::PFJet> > edm::Ptr<reco::PFCandidate>
reco::BaseTau        requires reco::RecoCandidate edm::RefVector<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> > ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> >
reco::RecoChargedCandidate requires reco::RecoCandidate edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> >
reco::RecoEcalCandidate requires reco::RecoCandidate edm::Ref<vector<reco::SuperCluster>,reco::SuperCluster,edm::refhelper::FindUsingAdvance<vector<reco::SuperCluster>,reco::SuperCluster> >
edm::Ref<vector<reco::SuperCluster>,reco::SuperCluster,edm::refhelper::FindUsingAdvance<vector<reco::SuperCluster>,reco::SuperCluster> > requires edm::RefCoreWithIndex
edm::Ref<vector<reco::TrackExtra>,reco::TrackExtra,edm::refhelper::FindUsingAdvance<vector<reco::TrackExtra>,reco::TrackExtra> > requires edm::RefCoreWithIndex
edm::reftobase::Holder<reco::Track,edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> > > requires edm::reftobase::BaseHolder<reco::Track> edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> >
edm::Ref<vector<reco::RecoEcalCandidate>,reco::RecoEcalCandidate,edm::refhelper::FindUsingAdvance<vector<reco::RecoEcalCandidate>,reco::RecoEcalCandidate> > requires edm::RefCoreWithIndex
edm::Ref<vector<reco::RecoChargedCandidate>,reco::RecoChargedCandidate,edm::refhelper::FindUsingAdvance<vector<reco::RecoChargedCandidate>,reco::RecoChargedCandidate> > requires edm::RefCoreWithIndex
edm::Ref<vector<reco::CaloJet>,reco::CaloJet,edm::refhelper::FindUsingAdvance<vector<reco::CaloJet>,reco::CaloJet> > requires edm::RefCoreWithIndex
edm::Ref<vector<reco::MET>,reco::MET,edm::refhelper::FindUsingAdvance<vector<reco::MET>,reco::MET> > requires edm::RefCoreWithIndex
edm::Ref<vector<reco::CaloMET>,reco::CaloMET,edm::refhelper::FindUsingAdvance<vector<reco::CaloMET>,reco::CaloMET> > requires edm::RefCoreWithIndex
edm::Ref<vector<reco::IsolatedPixelTrackCandidate>,reco::IsolatedPixelTrackCandidate,edm::refhelper::FindUsingAdvance<vector<reco::IsolatedPixelTrackCandidate>,reco::IsolatedPixelTrackCandidate> > requires edm::RefCoreWithIndex
edm::Ref<vector<l1extra::L1MuonParticle>,l1extra::L1MuonParticle,edm::refhelper::FindUsingAdvance<vector<l1extra::L1MuonParticle>,l1extra::L1MuonParticle> > requires edm::RefCoreWithIndex
edm::Ref<vector<reco::PFJet>,reco::PFJet,edm::refhelper::FindUsingAdvance<vector<reco::PFJet>,reco::PFJet> > requires edm::RefCoreWithIndex
edm::Ref<vector<reco::PFTau>,reco::PFTau,edm::refhelper::FindUsingAdvance<vector<reco::PFTau>,reco::PFTau> > requires edm::RefCoreWithIndex
edm::Ref<vector<reco::PFMET>,reco::PFMET,edm::refhelper::FindUsingAdvance<vector<reco::PFMET>,reco::PFMET> > requires edm::RefCoreWithIndex
edm::Ref<vector<reco::PFTauTagInfo>,reco::PFTauTagInfo,edm::refhelper::FindUsingAdvance<vector<reco::PFTauTagInfo>,reco::PFTauTagInfo> > requires edm::RefCoreWithIndex
SiStripRecHit1D      requires TrackerSingleRecHit
edm::Ref<vector<reco::GsfTrack>,reco::GsfTrack,edm::refhelper::FindUsingAdvance<vector<reco::GsfTrack>,reco::GsfTrack> > requires edm::RefCoreWithIndex
edm::Ref<vector<reco::GsfTrackExtra>,reco::GsfTrackExtra,edm::refhelper::FindUsingAdvance<vector<reco::GsfTrackExtra>,reco::GsfTrackExtra> > requires edm::RefCoreWithIndex
```

**Comment by jpivarski** [comment]
The automatic closure comes from the fact that I committed a fix to master. You can now load this file, but there's another bug preventing you from loading the TTree and looking at its branches, so I'm debugging that and will post a comment here when I'm done.

**Comment by jpivarski** [comment]
I'm losing my window in which to keep working on it. After the file is read in, an attempt to read the TTree (and not any branch data, just the TTree header itself) fails because I pass a compressed block of data to Python's ZLIB library, it doesn't complain, but the uncompressed block it returns is too small. The data in the uncompressed block is correct, up to the point where it cuts off, but I'm wondering if there's something wrong with (Python 3) ZLIB. I'll try other ZLIBs, but I have to get off the train now.

**Comment by jpivarski** [comment]
Got it! The original problem (dependency order for streamer info) was easy, and it turned out to be what I thought it was. But then there was another bug when trying to look at a GEN-SIM-DIGI-RAW TTree.

That was because the TTree data (without any data, just the description of all the branches) was greater than 16 MB and ROOT compresses object data in batches with a 3-byte header specifying the compressed and uncompressed size of each batch. Since this 3-byte uncompressed size maxes out at 16 MB, any object larger than this requires multiple batches. I didn't know this was a sequence— I thought there was only ever one batch (because the total compressed and uncompressed size is stated elsewhere— it didn't have to be batched).

So now you can open the file, look at the TTree, and even read some array data. For data types that are _currently_ supported, you have to look at the third column in "show", which specifies what Numpy or jagged array type it will be exported as.

```python
>>> import uproot
>>> f = uproot.open("/eos/cms/store/relval/CMSSW_9_4_0/RelValTTbar_13/GEN-SIM-DIGI-RAW/"
... "PU25ns_94X_upgrade2018_realistic_v5-v1/10000/3245F8B2-CBC8-E711-8FCA-0CC47A4D762E.root")
>>> t = f["Events"]
>>> t.show()
EventAuxiliary             TStreamerInfo              None
EventProductProvenance     TStreamerSTL               None
EventSelections            TStreamerSTL               None
BranchListIndexes          TStreamerSTL               asstlvector(asdtype('>u2'))
GenEventInfoProduct_generator__SIM.
                           TStreamerInfo              None
GenEventInfoProduct_generator__SIM.present
                           TStreamerBasicType         asdtype('bool')
GenEventInfoProduct_generator__SIM.obj
                           TStreamerObjectAny         None
...
```
```python
>>> t.array("float_hltFastPrimaryVertex__HLT.obj")
array([  8.04154873,   4.61222601,   3.10819483,   4.77717113,
         5.05367184,   7.31786966,   4.91463518,   4.09948969,
        13.52752304,   3.83071184,   3.7417469 ,   1.40437913,
        ...
```

It looks to me like this is an unsplit file: the branches with interesting names don't have an interpretation. If it's possible to make files like this with "splitlevel=99" in the TTree constructor (is that a CMSSW argument?), then more data will be available to you before I implement all those complex types.

(It would be more efficient for selective reading, too.)

This will be release 2.5.8 on both GitHub and PyPI.
