### ISSUE TITLE
Unable to open GEN-SIM-DIGI-RAW via xrootd interface

### ISSUE THREAD

**Issue by vkuznet** [scikit-hep/uproot#36]
While trying to use xrootd interface I'm unable to open the following file
/store/relval/CMSSW_9_4_0/RelValTTbar_13/GEN-SIM-DIGI-RAW/PU25ns_94X_upgrade2018_realistic_v5-v1/10000/3245F8B2-CBC8-E711-8FCA-0CC47A4D762E.root

```
Traceback (most recent call last):
  File "./tfaas.py", line 57, in listBranches
    with uproot.open(fin) as tree:
  File "/afs/cern.ch/work/v/valya/uproot-2.1.5/uproot/rootio.py", line 62, in open
    return xrootd(path, xrootdsource)
  File "/afs/cern.ch/work/v/valya/uproot-2.1.5/uproot/rootio.py", line 68, in xrootd
    return ROOTDirectory.read(xrootdsource(path), **options)
  File "/afs/cern.ch/work/v/valya/uproot-2.1.5/uproot/rootio.py", line 100, in read
    magic, fVersion = cursor.fields(source, ROOTDirectory._format1)
  File "/afs/cern.ch/work/v/valya/uproot-2.1.5/uproot/source/cursor.py", line 72, in fields
    return format.unpack(source.data(start, stop))
  File "/afs/cern.ch/work/v/valya/uproot-2.1.5/uproot/source/chunked.py", line 84, in data
    chunk = self._cache[chunkindex]
  File "/afs/cern.ch/work/v/valya/uproot-2.1.5/uproot/cache/memorycache.py", line 340, in __getitem__
    return super(ThreadSafeMemoryCache, self).__getitem__(key)
  File "/afs/cern.ch/work/v/valya/uproot-2.1.5/uproot/cache/memorycache.py", line 82, in __getitem__
    value = self.spillover[key]
IndexError: tuple index out of range
```

**Comment by jpivarski** [comment]
I wasn't able to exactly reproduce your setup because I don't know the hostname/port of the XRootD server on which this file resides. However, I was able to construct a very similar situation with the same file and reproduced the bug.

It's now fixed. One API evolved ahead of the other, and this feature isn't in the build tests yet.

So you can now use XRootD, and here's a hint: XRootD does not by itself cache connections, so uproot has to maintain a cache. The parameters of this cache have not been tuned. You can set them differently by using some of the more eclectic arguments to the `uproot.open` function or you can change them after the fact (possibly in response to observed slow-downs):

```python
>>> import uproot
>>> f = uproot.open("root://cmsxrootd.fnal.gov//store/user/pivarski/TrackResonanceNtuple.root")
>>> t = f["TrackResonanceNtuple/twoMuon"]
>>> t.array("px")   # slow
>>> t.array("px")   # fast
>>> f.source.cache.limitbytes
1048576
>>> f.source.cache.numbytes
105952L
>>> f.source.cache.limitbytes = 1024   # 1 kB of cache? are you nuts?
>>> t.array("py")   # slow
>>> t.array("py")   # slow
>>> f.source.cache.limitbytes = 1024**2   # 1 MB is a little better
>>> t.array("py")   # slow
>>> t.array("py")   # fast
```

Release 2.5.9.
