### ISSUE TITLE
Error reading stl vector from root file

### ISSUE THREAD

**Issue by rklasen** [scikit-hep/uproot#373]
Hi,

I'm trying to read an `stl:vector` of numbers from a `TBranch` inside a root file. The file in genereal looks like this:

```
trackFile = uproot.open('Lumi_Track_100000.root')
print(f'Your file looks like this:\n')
trackFile[b"pndsim"].show()
```

This is the shortend output:

```
EventHeader.               TStreamerInfo              asgenobj(FairEventHeader)
LMDPndTrack                TStreamerInfo              asdtype('>i4')
[...]
LMDPndTrack.fTrackParamLast.fiver
                           TStreamerInfo              asjagged(asobj(<uproot_methods.classes.TVector3.Methods>))
[...]
LMDPndTrack.fTrackCand.fHitId
                           TStreamerSTL               asjagged(astable(asdtype("[('fFile', 'u1'), ('fType', '>u2'), ('fEntry', '>i4'), ('fIndex', '>i4'), ('fWeight', '>f4'), ('fRho', '>f8')]")), 10)
[...]
```

And I can access a sub branch just fine:

```
Access some sub branch:
 [[TVector3(0.04001, -3.4694e-18, 0.9992) TVector3(0.04001, -3.4694e-18, 0.9992) 
[...]
TVector3(0.04001, -3.4694e-18, 0.9992) TVector3(0.04001, -3.4694e-18, 0.9992)]]
```

However, the important branch access fails:

```
Traceback (most recent call last):
  File "./trackCandMinimal.py", line 11, in <module>
    print(f'Access the important sub branch:\n { trackFile[b"pndsim"].array("LMDPndTrack.fTrackCand.fHitId") }\n\n')
  File "/usr/local/lib/python3.6/dist-packages/uproot/tree.py", line 513, in array
    return tbranch.array(interpretation=interpretation, entrystart=entrystart, entrystop=entrystop, flatten=flatten, awkwardlib=awkwardlib, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=blocking)
  File "/usr/local/lib/python3.6/dist-packages/uproot/tree.py", line 1386, in array
    basket_itemoffset = self._basket_itemoffset(interpretation, basketstart, basketstop, keycache)
  File "/usr/local/lib/python3.6/dist-packages/uproot/tree.py", line 1341, in _basket_itemoffset
    numitems = interpretation.numitems(key.border, self.basket_numentries(i))
  File "/usr/local/lib/python3.6/dist-packages/uproot/interp/jagged.py", line 64, in numitems
    return self.content.numitems(numbytes - numentries * self.skipbytes, numentries)
  File "/usr/local/lib/python3.6/dist-packages/uproot/interp/objects.py", line 158, in numitems
    return self.content.numitems(numbytes, numentries)
  File "/usr/local/lib/python3.6/dist-packages/uproot/interp/numerical.py", line 152, in numitems
    assert remainder == 0
AssertionError
```

It seems the interpretation of this branch is wrong, it's not supposed to be `astable`, but like a `SimpleArray` or something. I can not use `awkward.fromiter`, because the assertion fails as soon ass I try to access the `TBranch`. So the important thing I guess is:

**Can I force the interpretation of a TBranch as a vector, array, something else?**

I created a minimal running example here:

```python
#!/usr/bin/env python3

import numpy as np
import uproot

trackFile = uproot.open('Lumi_Track_100000.root')
print(f'Your file looks like this:\n')
trackFile[b"pndsim"].show()
print(f'\n\n')
print(f'Access some sub branch:\n { trackFile[b"pndsim"].array("LMDPndTrack.fTrackParamLast.fiver") }\n\n')
print(f'Access the important sub branch:\n { trackFile[b"pndsim"].array("LMDPndTrack.fTrackCand.fHitId") }\n\n')
```

[And the track file can be downloaded from my Dropbox.](https://www.dropbox.com/s/uh51fk72stthi79/Lumi_Track_100000.root?dl=0)

Thank you!

**Comment by jpivarski** [comment]
Yes, it's possible to provide an alternate `Interpretation`: that's the first argument after specifying which branch you'd like to read (or if specifying multiple branches, you can give it a dict of branch name, `Interpretation` pairs).

However, I'm looking at this file, and I don't see how the branch is _supposed_ to be interpreted. When I look at the streamers and the class name on the branch, it looks like the right `Interpretation` to me. However, the size of the data is completely wrong.

(The reason you're seeing an `asjagged(astable)` interpretation, rather than `asgenobj` with `SimpleArray` or something, is because the structure—according to the streamers, at least—has fixed size and can therefore be read into a Numpy record array. This is faster than iterating over the data with generated Python code, which is what `asgenobj` does.)

To try to interpret it, let's first look at the streamers. The enclosing class shows that `fHitId` is a `std::vector`, so either `asjagged` with `skipbytes=10` or `asgenobj(STLVector)` with `skipbytes=6` should be appropriate, not `SimpleArray`. (`SimpleArray` is for C-style arrays, which don't have any header, not C++ `std::vector`, which has a 6-byte header and 4-byte size.)

```
>>> f._context.streamerinfosmap[b"PndTrackCand"].show()
StreamerInfo for class: PndTrackCand, version=3, checksum=0x5795773d
  FairTimeStamp   BASE            offset=  0 type= 0 
  fHitId          vector<PndTrackCandHit> offset=  0 type=500 first index is detId, second index is hit Id
  sorted          bool            offset=  0 type=18 
  fMcTrackId      int             offset=  0 type= 3 track id for MC simulation
  fVerbose        int             offset=  0 type= 3 
```

Next, we look at the hit's class and its superclass:

```
>>> f._context.streamerinfosmap[b"PndTrackCandHit"].show()
StreamerInfo for class: PndTrackCandHit, version=2, checksum=0xe549bf3e
  FairLink        BASE            offset=  0 type= 0 
  fRho            double          offset=  0 type= 8 sorting parameter

>>> f._context.streamerinfosmap[b"FairLink"].show()
StreamerInfo for class: FairLink, version=5, checksum=0x559c3d7a
  fFile           unsigned char   offset=  0 type=11 
  fType           unsigned short  offset=  0 type=12 
  fEntry          int             offset=  0 type= 3 
  fIndex          int             offset=  0 type= 3 
  fWeight         float           offset=  0 type= 5 
```

From this, it looks like each `PndTrackCandHit` should be exactly 23 bytes, justifying the default `Interpretation`.

```
>>> t["LMDPndTrack.fTrackCand.fHitId"].interpretation
asjagged(astable(asdtype("[('fFile', 'u1'), ('fType', '>u2'), ('fEntry', '>i4'), ('fIndex', '>i4'), ('fWeight', '>f4'), ('fRho', '>f8')]")), 10)
```

But let's do this with `asgenobj(STLVector)` anyway, just to show how you can pass a custom `Interpretation`.

```
>>> newinterp = uproot.asgenobj(uproot.STLVector(f._context.classes["PndTrackCandHit"]), t["LMDPndTrack.fTrackCand.fHitId"]._context, 6)
>>> newinterp
asgenobj(STLVector(PndTrackCandHit))
```

Unfortunately, this doesn't work:

```
>>> t["LMDPndTrack.fTrackCand.fHitId"].array(newinterp)
Traceback (most recent call last):
...
  File "/home/pivarski/irishep/uproot/uproot/source/source.py", line 41, in data
    raise IndexError("indexes {0}:{1} are beyond the end of data source of length {2}".format(start, stop, len(self._source)))
IndexError: indexes 3221225502:3221225508 are beyond the end of data source of length 386
```

It's trying to read off the end of the file because this `Interpretation` isn't correct.

To try to figure out the right `Interpretation` (a necessary step before adding a rule to automatically identify it), I usually start by looking at the raw bytes of one event, for which we have a handy `Interpretation` named `asdebug`:

```
>>> t["LMDPndTrack.fTrackCand.fHitId"].array(uproot.asdebug)[0]
array([ 64,   0,   1, 132,  64,   9,   0,   2,   0,   0,   0,   4,   0,
         0,   0,   0,   0,   2,   0,   2,   0,   2,   0,   2, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255,   0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   2,
         0,   0,   0,   3,  63, 128,   0,   0,  63, 128,   0,   0,  63,
       128,   0,   0,  63, 128,   0,   0,  64, 145,  36,  47, 160,   0,
         0,   0,  64, 145, 116,  26, 128,   0,   0,   0,  64, 145, 156,
        15, 128,   0,   0,   0,  64, 145, 196,   4,  96,   0,   0,   0,
         0,   0,   0,   4,   0,   0,   0,   0,   0,   2,   0,   2,   0,
         2,   0,   2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255,   0,   0,   0,   1,   0,   0,   0,
         0,   0,   0,   0,   2,   0,   0,   0,   3,  63, 128,   0,   0,
        63, 128,   0,   0,  63, 128,   0,   0,  63, 128,   0,   0,  64,
       145,  36,  47, 160,   0,   0,   0,  64, 145, 116,  26, 128,   0,
         0,   0,  64, 145, 156,  15, 128,   0,   0,   0,  64, 145, 196,
         4,  96,   0,   0,   0,   0,   0,   0,   4,   0,   0,   0,   0,
         0,   2,   0,   2,   0,   2,   0,   2, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,   0,   0,
         0,   1,   0,   0,   0,   0,   0,   0,   0,   2,   0,   0,   0,
         3,  63, 128,   0,   0,  63, 128,   0,   0,  63, 128,   0,   0,
        63, 128,   0,   0,  64, 145,  36,  47, 160,   0,   0,   0,  64,
       145, 116,  26, 128,   0,   0,   0,  64, 145, 156,  15, 128,   0,
         0,   0,  64, 145, 196,   4,  96,   0,   0,   0,   0,   0,   0,
         4,   0,   0,   0,   0,   0,   2,   0,   2,   0,   2,   0,   2,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255,   0,   0,   0,   1,   0,   0,   0,   0,   0,   0,
         0,   2,   0,   0,   0,   3,  63, 128,   0,   0,  63, 128,   0,
         0,  63, 128,   0,   0,  63, 128,   0,   0,  64, 145,  36,  47,
       160,   0,   0,   0,  64, 145, 116,  26, 128,   0,   0,   0,  64,
       145, 156,  15, 128,   0,   0,   0,  64, 145, 196,   4,  96,   0,
         0,   0], dtype=uint8)
>>> t["LMDPndTrack.fTrackCand.fHitId"].array(uproot.asdebug)[1]
array([64,  0,  0,  4, 64,  9,  0,  2], dtype=uint8)
>>> t["LMDPndTrack.fTrackCand.fHitId"].array(uproot.asdebug)[2]
array([64,  0,  0,  4, 64,  9,  0,  2], dtype=uint8)
```

One thing that's odd about this is that it's supposed to be a `std::vector`, which must have at least 10 bytes: 6-byte header plus 4-byte size. However, events 1 and 2 are 8 bytes? What's the distribution of sizes?

```
import collections
>>> c = collections.Counter()
>>> for x in t["LMDPndTrack.fTrackCand.fHitId"].array(uproot.asdebug):
...     c[len(x)] += 1
... 
>>> for numbytes, count in sorted(c.items()):
...     print(numbytes, count)
... 
8 35795
81 14
154 4036
227 37
300 165
392 59303
446 41
465 4
519 2
538 83
592 46
684 55
738 10
776 251
830 2
884 11
922 4
976 15
1068 6
1122 1
1141 1
1160 43
1176 5
1268 3
1452 1
1544 29
1560 2
1598 1
1690 3
1760 3
1928 10
2017 1
2036 1
2312 6
2696 1
2928 1
3080 2
3188 1
4578 1
4616 1
6152 3
```

Presumably the 8-byte events are "empty." If that means that there's an 8-byte header, we should get the data size by subtracting off 8. The next bigger size is 81 bytes, and 81 - 8 is 73, which is prime, so it can't be a multiple of repeated elements. Could the class size really be 73 bytes? Looking at the streamers, we could only account for 23 bytes. Some of the sizes above divide evenly into 73, but many others don't.

```
>>> sorted([(x - 8)/73.0 for x in c.keys()])
[0.0, 1.0, 2.0, 3.0, 4.0, 5.260273972602739, 6.0, 6.260273972602739, 7.0, 7.260273972602739, 8.0, 9.26027397260274, 10.0, 10.520547945205479, 11.26027397260274, 12.0, 12.520547945205479, 13.26027397260274, 14.520547945205479, 15.26027397260274, 15.520547945205479, 15.780821917808218, 16.0, 17.26027397260274, 19.78082191780822, 21.041095890410958, 21.26027397260274, 21.78082191780822, 23.041095890410958, 24.0, 26.301369863013697, 27.52054794520548, 27.78082191780822, 31.561643835616437, 36.821917808219176, 40.0, 42.082191780821915, 43.56164383561644, 62.602739726027394, 63.12328767123287, 84.16438356164383]
```

Is the class size variable? That should only be possible if it contains an array/`std::vector` of its own, or maybe a string. The streamers say nothing about anything like that.

Here's another thought: the `PndTrackCandHit` is supposed to end with an 8-byte floating-point number. Does it at least do that?

```
>>> t["LMDPndTrack.fTrackCand.fHitId"].array(uproot.asdebug)[:, -8:].regular().view(">f8")
array([[1137.00427246],
       [   2.00000811],
       [   2.00000811],
       ...,
       [   2.00000811],
       [1137.8840332 ],
       [1137.0690918 ]])
```

That looks pretty good—when floating-point numbers are incorrectly interpreted, they usually aren't so close to 1, logarithmically.

But on the whole, I'm at a loss. I don't know how to interpret the data in that branch. I understand how the default `Interpretation` comes from the streamers—that looks right to me—but I don't understand how the data in the branch is anything like what the streamer says it should be.

**Comment by rklasen** [comment]
Thank you for your detailed answer! 

These values look like our detector dimensions, so this interpretation seems realistic.

```
>>> t["LMDPndTrack.fTrackCand.fHitId"].array(uproot.asdebug)[:, -8:].regular().view(">f8")
array([[1137.00427246],
       [   2.00000811],
       [   2.00000811],
       ...,
       [   2.00000811],
       [1137.8840332 ],
       [1137.0690918 ]])
```

If I understand correctly, the problem is that the `PndTrackCandHit` class has variable size, and this can indeed be true:

```
// Description:
//      Implementation of class PndTrackCand
//      see PndTrackCand.hh for details
//
// Environment:
//      Software developed for the PANDA Detector at FAIR.
//
// Author List:
//      Tobias Stockmanns (IKP - Juelich) during the Panda Meeting 03/09

#ifndef PNDTRACKCANDHIT_HH
#define PNDTRACKCANDHIT_HH

// Root Class Headers ----------------
#include "TObject.h"

#include "FairLink.h"

#include <iostream>
#include <vector>
#include <map>

#ifndef __CINT__
#include <boost/serialization/access.hpp>
#include <boost/serialization/base_object.hpp>
#endif //__CINT__

class PndTrackCandHit : public FairLink{
public:
  PndTrackCandHit():FairLink(), fRho(0){}
  PndTrackCandHit(Int_t detId, Int_t hitId, Double_t rho):FairLink(detId, hitId), fRho(rho){}
  PndTrackCandHit(FairLink& link, Double_t& rho):FairLink(link), fRho(rho){};
  virtual ~PndTrackCandHit() {}
  bool operator< (const PndTrackCandHit& rhs) const
  {return fRho<rhs.fRho;};
  bool operator> (const PndTrackCandHit& rhs) const
  {return fRho>rhs.fRho;};
  bool operator<= (const PndTrackCandHit& rhs) const
  {return fRho<=rhs.fRho;};
  bool operator>= (const PndTrackCandHit& rhs) const
  {return fRho>=rhs.fRho;};
  bool operator== (const PndTrackCandHit& hit) const {
    return ( FairLink::operator==((FairLink)hit) && fRho == hit.fRho);
  }
  bool operator!= (const PndTrackCandHit& hit) const {
    return (!(FairLink::operator==(hit)));
  }
  Int_t GetHitId()const {return GetIndex();}
  Int_t GetDetId()const {return GetType();}
  Double_t GetRho()const {return fRho;}

  void Print() const;

#ifndef __CINT__ // for BOOST serialization
  template<class Archive>
  void serialize(Archive & ar, const unsigned int version)
  	{
  		ar & boost::serialization::base_object<FairLink>(*this);
  		ar & fRho;
  	}
#endif // for BOOST serialization

  private :
  Double_t fRho;		///< sorting parameter

  ClassDef(PndTrackCandHit,2);
};
#endif
```

Which inherits from [`FairLink`](https://github.com/FairRootGroup/FairRoot/blob/master/base/event/FairLink.h), which **does not** inherit from `TObject`. I'm not sure if the streamer has trouble with objects that do not inherit from `TObject`.  

`FairLink` uses [`unsigned short`s](https://github.com/FairRootGroup/FairRoot/blob/master/base/event/FairLink.h#L122) and we've had trouble in the past in that STL vectors try to optimize their internal structure if bools or unsigned shorts are the data type. In our case, `std::vectors` are no longer thread safe when `bool`s are stored in them.

I'm afraid I don't know enough about this class, but ROOTs `TBrowser` interprets the fIndex values as (vectors of) doubles, and this is what I'm looking for as well.

![Root TBrowser](https://i.imgur.com/6POcNn1.png)

**Comment by jpivarski** [comment]
Streamers shouldn't have a problem with classes that don't inherit from `TObject`. (I'm pretty sure we've handled a lot of classes that don't inherit from `TObject` already.)

It looks like the biggest mystery is `FairLink`: `PndTrackCandHit` only adds an 8-byte floating point number to the end of each `FairLink` (confirmed by your C++ class) and we find that floating point number every time. As you say, the values of `fRho` look realistic. That just leaves the rest of the `FairLink`.

Despite what the streamer written to the ROOT file says, this field (minus the `fRho` added by `PndTrackCandHit`) can be as small as zero bytes. This is in contradiction with the `PndTrackCand` streamer that says it's a `std::vector`. Do `PndTrackCand` and `PndTrackCandHit` have custom streamers—a C++ method that explicitly specifies how to serialize itself, in which case the `TStreamerInfo` objects are irrelevant or out-of-date? If you're using custom streamers, no process other than the original C++ code can deserialize them; to get these objects in Python, one would have to write the custom streamers manually (as I do for some core ROOT classes, mostly those that predate the `TStreamerInfo` mechanism).

This is a question about the `FairLink` class, which might be defined outside of your codebase.

**Comment by rklasen** [comment]
We inherit the `FairLink` from FairRoot, the definition is here: https://github.com/FairRootGroup/FairRoot/blob/master/base/event/FairLink.h#L111. From the includes, it seems they use `boost::serialization` , and the actual implementation seems to be:

```cpp
template<class Archive>
        void serialize(Archive& ar, const unsigned int)
        {
            ar& fFile;
            ar& fType;
            ar& fEntry;
            ar& fIndex;
            ar& fWeight;
        }


  private:
    unsigned char fFile;
    unsigned short fType;
    int fEntry;
    int fIndex;
    float fWeight;
```

Can this be recreated in python in general?

**Comment by rklasen** [comment]
Alright, I'll try. Thank you for your help!

**Comment by sbinet** [comment]
AFAICT, `FairLink` has the `ClassDefNV` macro and there's a `LinkDef.h`:
https://github.com/FairRootGroup/FairRoot/blob/master/base/FairLinkDef.h

so there must be a dict+streamer defined somewhere.

as far as boost serialization is concerned, I had to reverse engineer part of it for the [alice-go/fer](https://github.com/alice-go/fer) control framework (compatible with `FairMQ`):
- https://github.com/go-boostio/boostio

it's not *that* complicated.

**Comment by jpivarski** [comment]
@sbinet I didn't mean that it's going to be too complicated, just that Boost serialization is way out of scope for uproot. It would need to be a separate project, like go-boostio.  :)

In #374, @rklasen said that it would be a big deal to get `fIndex` values, so I dug into it. As it turns out, the data are internally split (split _within_ the event) in groups of 3 or 4, with an integer prefix before each block of contiguous columns. I'm not sure if the separation of these blocks is relevant (it might just be "paging"), but the following preserves that structure. (Replace `append` with `extend` to ignore this paging.)

```python
import uproot, struct, numpy

tree = uproot.open("issue373.root")["pndsim"]
branch = tree["LMDPndTrack.fTrackCand.fHitId"]

class PndTrackCandHit(uproot.rootio.ROOTStreamedObject):
    _first_format = struct.Struct(">d")
    _n_format = struct.Struct(">i")
    _fFile_dtype = numpy.dtype("u1")
    _fType_dtype = numpy.dtype(">u2")
    _fEntry_dtype = numpy.dtype(">i4")
    _fIndex_dtype = numpy.dtype(">i4")
    _fWeight_dtype = numpy.dtype(">f4")
    _fRho_dtype = numpy.dtype(">f8")

    @classmethod
    def _readinto(cls, self, source, cursor, context, parent):
        self.first = cursor.field(source, self._first_format)
        self.fFile = []
        self.fType = []
        self.fEntry = []
        self.fIndex = []
        self.fWeight = []
        self.fRho = []
        while True:
            try:
                n = cursor.field(source, self._n_format)
                fFile = cursor.array(source, n, self._fFile_dtype)
                fType = cursor.array(source, n, self._fType_dtype)
                fEntry = cursor.array(source, n, self._fEntry_dtype)
                fIndex = cursor.array(source, n, self._fIndex_dtype)
                fWeight = cursor.array(source, n, self._fWeight_dtype)
                fRho = cursor.array(source, n, self._fRho_dtype)
            except IndexError:
                break
            else:
                self.fFile.append(fFile)
                self.fType.append(fType)
                self.fEntry.append(fEntry)
                self.fIndex.append(fIndex)
                self.fWeight.append(fWeight)
                self.fRho.append(fRho)
        return self

interp = uproot.asgenobj(PndTrackCandHit, branch._context, skipbytes=0)
branch.array(interp)
```

So, to get the `fIndex` values,

```python
>>> for a in branch.array(interp):
...     print(a.fIndex)
... 
[array([1, 0, 2, 3], dtype=int32), array([1, 0, 2, 3], dtype=int32), array([1, 0, 2, 3], dtype=int32), array([1, 0, 2, 3], dtype=int32)]
[]
[]
[array([0, 2, 1], dtype=int32), array([0, 2, 1], dtype=int32)]
[array([0, 1, 2], dtype=int32), array([0, 1, 2], dtype=int32)]
[]
[]
[array([0, 1, 3, 2], dtype=int32), array([0, 1, 3, 2], dtype=int32), array([0, 1, 3, 2], dtype=int32), array([0, 1, 3, 2], dtype=int32)]
[array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32)]
[array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32)]
[array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32)]
[array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32)]
[array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32)]
[array([0, 1, 2, 3], dtype=int32), array([0, 1, 2, 3], dtype=int32), array([0, 1, 2, 3], dtype=int32), array([0, 1, 2, 3], dtype=int32)]
[array([1, 0, 2, 3], dtype=int32), array([1, 0, 2, 3], dtype=int32), array([1, 0, 2, 3], dtype=int32), array([1, 0, 2, 3], dtype=int32)]
[]
[array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32)]
[array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32), array([1, 0, 3, 2], dtype=int32)]
...
```

**Comment by jpivarski** [comment]
(By the way, @rklasen, your [screenshot](https://github.com/scikit-hep/uproot/issues/373#issuecomment-539588241) was highly useful in reverse-engineering this. The histogram showed that often `fIndex == 3`, which is not an integer you're likely to get "by accident" (unlike `0`, `1`, and `2`). So I searched for integers that are `3`, then noticed that many of them are followed by a floating point `1.0`, which makes a lot of sense as an `fWeight`, and then pieced it together from there. So the histogram really was helpful; thanks!)

**Comment by rklasen** [comment]
Thank you so much! With this, and your answer from #374, I have enough to get the rest on my own. 

The clustering of the data into either 3 or 4 values is sensible, from what I can see in your code, those are the indices I'm looking for. They come from the reco hits, that means every event can have either zero, two or four tracks. If an event has two tacks, then there were 3 reco hits (which have some x, y and z values and the fIndex which is so important for me), and if an event has four tracks, then there are four reco hits. Actually, the tracks were fitted from the reco hits and not the other way round, but this data is from a late stage of the simulation chain, and the tracks carry with them the information from which possible track candidate they come from (one candidate per track), and the candidate carries the information from which reco hit is was fit.

So, with the class and the classmethod you provided, I can get these indices and probably the x, y, and z coordinates from the tracks as well.

Thank you again, this is immensely helpful!

**Comment by jpivarski** [comment]
As it turns out, the error above is because I was unaware of ROOT's "memberwise splitting," and (if I said anything to the contrary above), it has nothing to do with Boost serialization. This same error came up in 6 different issues, so further discussion on it will be consolidated into scikit-hep/uproot4#38. (This comment is a form message I'm writing on all 6 issues.)

As of PR scikit-hep/uproot4#87, we can now _detect_ such cases, so at least we'll raise a `NotImplementedError` instead of letting the deserializer fail in mysterious ways. Someday, it will actually be implemented (watch scikit-hep/uproot4#38), but in the meantime, the thing you can do is write your data "objectwise," not "memberwise." (See [this comment](https://github.com/scikit-hep/uproot4/issues/38#issuecomment-682686940) for ideas on how to do that, and if you manage to do it, you can help a lot of people out by sharing a recipe.)
