### ISSUE TITLE
vector<bool> not supported

### ISSUE THREAD

**Issue by lgiommi** [scikit-hep/uproot#45]
Hi,
I've seen that in uproot is not supported the type vector<bool> when I try to read one of them from a root file. Let me show you an example. I run this code
```
import uproot
t=uproot.open("/afs/cern.ch/work/b/bonacor/public/small10kevts.root")["events"]
t.show()
for (array,) in t.iterate("triggerBit", entrysteps=1000, outputtype=tuple):
    print len(array)
```
and I have this output
```
runNo                      (no streamer)              asdtype('>i4')
evtNo                      (no streamer)              asdtype('>i4')
lumi                       (no streamer)              asdtype('>i4')
nvtx                       (no streamer)              asdtype('>i4')
nJets                      (no streamer)              asdtype('>i4')
nLeptons                   (no streamer)              asdtype('>i4')
nBJets                     (no streamer)              asdtype('>i4')
category                   (no streamer)              asdtype('>i4')
rho                        (no streamer)              asdtype('>f4')
ht                         (no streamer)              asdtype('>f4')
mva                        (no streamer)              asdtype('>f4')
met                        (no streamer)              asdtype('>f4')
metSig                     (no streamer)              asdtype('>f4')
mJJ                        (no streamer)              asdtype('>f4')
yJJ                        (no streamer)              asdtype('>f4')
ptJJ                       (no streamer)              asdtype('>f4')
dRJJ                       (no streamer)              asdtype('>f4')
dPhiJJ                     (no streamer)              asdtype('>f4')
dPhiLJ                     (no streamer)              asdtype('>f4')
jetIsBtag                  TStreamerSTL               None
jetFlavor                  TStreamerSTL               asstlvector(asdtype('>i4'))
jetFlavorHadron            TStreamerSTL               asstlvector(asdtype('>i4'))
jetNSub                    TStreamerSTL               asstlvector(asdtype('>i4'))
jetNBSub                   TStreamerSTL               asstlvector(asdtype('>i4'))
jetPt                      TStreamerSTL               asstlvector(asdtype('>f4'))
jetBtag                    TStreamerSTL               asstlvector(asdtype('>f4'))
jetEta                     TStreamerSTL               asstlvector(asdtype('>f4'))
jetPhi                     TStreamerSTL               asstlvector(asdtype('>f4'))
jetMass                    TStreamerSTL               asstlvector(asdtype('>f4'))
jetMassSoftDrop            TStreamerSTL               asstlvector(asdtype('>f4'))
jetChf                     TStreamerSTL               asstlvector(asdtype('>f4'))
jetNhf                     TStreamerSTL               asstlvector(asdtype('>f4'))
jetPhf                     TStreamerSTL               asstlvector(asdtype('>f4'))
jetMuf                     TStreamerSTL               asstlvector(asdtype('>f4'))
jetElf                     TStreamerSTL               asstlvector(asdtype('>f4'))
jetTau1                    TStreamerSTL               asstlvector(asdtype('>f4'))
jetTau2                    TStreamerSTL               asstlvector(asdtype('>f4'))
jetTau3                    TStreamerSTL               asstlvector(asdtype('>f4'))
jetBtagSub0                TStreamerSTL               asstlvector(asdtype('>f4'))
jetBtagSub1                TStreamerSTL               asstlvector(asdtype('>f4'))
jetMassSub0                TStreamerSTL               asstlvector(asdtype('>f4'))
jetMassSub1                TStreamerSTL               asstlvector(asdtype('>f4'))
jetPtSub0                  TStreamerSTL               asstlvector(asdtype('>f4'))
jetPtSub1                  TStreamerSTL               asstlvector(asdtype('>f4'))
jetEtaSub0                 TStreamerSTL               asstlvector(asdtype('>f4'))
jetEtaSub1                 TStreamerSTL               asstlvector(asdtype('>f4'))
jetPhiSub0                 TStreamerSTL               asstlvector(asdtype('>f4'))
jetPhiSub1                 TStreamerSTL               asstlvector(asdtype('>f4'))
jetFlavorSub0              TStreamerSTL               asstlvector(asdtype('>i4'))
jetFlavorSub1              TStreamerSTL               asstlvector(asdtype('>i4'))
jetFlavorHadronSub0        TStreamerSTL               asstlvector(asdtype('>i4'))
jetFlavorHadronSub1        TStreamerSTL               asstlvector(asdtype('>i4'))
lepId                      TStreamerSTL               asstlvector(asdtype('>i4'))
lepPt                      TStreamerSTL               asstlvector(asdtype('>f4'))
lepEta                     TStreamerSTL               asstlvector(asdtype('>f4'))
lepPhi                     TStreamerSTL               asstlvector(asdtype('>f4'))
lepE                       TStreamerSTL               asstlvector(asdtype('>f4'))
lepIso                     TStreamerSTL               asstlvector(asdtype('>f4'))
triggerBit                 TStreamerSTL               None
triggerPre                 TStreamerSTL               asstlvector(asdtype('>i4'))
Traceback (most recent call last):
  File "solution.py", line 7, in <module>
    for (array,) in t.iterate("triggerBit", entrysteps=1000, outputtype=tuple):
  File "/afs/cern.ch/user/b/bonacor/.local/lib/python2.6/site-packages/uproot-2.5.17-py2.6.egg/uproot/tree.py", line 415, in iterate
    branches = list(self._normalize_branches(branches))
  File "/afs/cern.ch/user/b/bonacor/.local/lib/python2.6/site-packages/uproot-2.5.17-py2.6.egg/uproot/tree.py", line 507, in _normalize_branches
    raise ValueError("cannot interpret branch {0} as a Python type".format(repr(name)))
ValueError: cannot interpret branch 'triggerBit' as a Python type
```
So triggerBit is a TStreamerSTL of an unknown type but, if I inspect the root file using the Print() function on the tree events, I can see that 
```
*............................................................................*
*Br   58 :triggerBit : vector<bool>                                          *
*Entries :    10000 : Total  Size=     241281 bytes  File Size  =      38703 *
*Baskets :        9 : Basket Size=      32000 bytes  Compression=   6.22     *
*............................................................................*
```
Actually triggerBit should be a vector of 10 elements (where each one is 0 or 1), because if I inspect this branch there are 100000 entries and not 10000. So what happens? Seems that uproot didn't recognise the vector<bool> type, right?

Thanks
Luca

@vkuznet

**Comment by jpivarski** [comment]
Sorry I missed this— uproot doesn't do anything special for `vector<bool>`, and that's probably the problem. In the C++ STL, `vector<bool>` is special: the data are packed (one bit per value, rather than one byte). That will require specialized code in uproot to call `numpy.unpackbits` for this case.

**Comment by jpivarski** [comment]
I've submitted a fix to this in GitHub, but I'm having trouble deploying it to PyPI.

**Comment by jpivarski** [comment]
On PyPI as 2.5.21.

**Comment by lgiommi** [comment]
Thank you very much again! I've just verified that now uproot works also for vector<bool>
