### ISSUE TITLE
uproot.update is not functional

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/uproot#460]
If you look at the lines here

https://github.com/scikit-hep/uproot/blob/6b7e886efc0720a20b3622a5b2840cb1fa0558bc/uproot/write/TFile.py#L27-L40

running `uproot.update` on an existing ROOT file causes a crash like so:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "run.py", line 13, in process_file
    with uproot.update(output_fname) as out_file:
  File "/afs/cern.ch/user/g/gstark/pyhf/lib64/python3.6/site-packages/uproot/write/TFile.py", line 29, in __init__
    self._openfile(path)
TypeError: _openfile() missing 1 required positional argument: 'compression'
```

this is because the call to `_openfile` in the `__init__` seems to only specify one positional argument here.

**Comment by jpivarski** [comment]
The "update" writing uproot is supposed to be `NotImplementedError`. @reikdas?

**Comment by reikdas** [comment]
The naive way(and the way which seems more appropriate to me) to solve this problem is to comment out the `_openfile()` call in TFileUpdate's `__init__` method. Once someone starts working on TFileUpdate, they can uncomment the code and fix it as required. This is in branch write-update - https://github.com/scikit-hep/uproot/compare/write-update

The other way would be to do this - 
```
index b8dc164..0bff324 100644
--- a/uproot/write/TFile.py
+++ b/uproot/write/TFile.py
@@ -25,8 +25,8 @@ from uproot.write.objects.util import Util
 from uproot.write.objects.TTree import TTree
 
 class TFileUpdate(object):
-    def __init__(self, path):
-        self._openfile(path)
+    def __init__(self, path, compression=uproot.write.compress.ZLIB(1)):
+        self._openfile(path, compression)
         raise NotImplementedError
 
     def _openfile(self, path, compression):
@@ -203,6 +203,11 @@ class TFileUpdate(object):
     def __exit__(self, type, value, traceback):
         self.close()
 
+    @compression.setter
+    def compression(self, value):
+        self._compression = value
+
+
 class TFileRecreate(TFileUpdate):
     def __init__(self, path, compression=uproot.write.compress.ZLIB(1)):
         self._openfile(path, compression)
```

@jpivarski Which do you prefer?
