### ISSUE TITLE
Unable to read Float16_t or Double32_t type branches

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/uproot#516]
uproot doesn't seem able to read branches of the types `Float16_t` (`/f` in the leaflist) and `Double32_t` (`/d` in the leaflist):

```python
>>> uproot.open('file.root')['tree']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/uproot/rootio.py", line 225, in __getitem__
    return self.get(name)
  File "/usr/lib/python3.8/site-packages/uproot/rootio.py", line 359, in get
    return last.get()
  File "/usr/lib/python3.8/site-packages/uproot/rootio.py", line 1038, in get
    return _classof(self._context, self._fClassName).read(self._source, self._cursor.copied(), self._context, self)
  File "/usr/lib/python3.8/site-packages/uproot/rootio.py", line 978, in read
    out._postprocess(source, cursor, context, parent)
  File "/usr/lib/python3.8/site-packages/uproot/tree.py", line 307, in _postprocess
    branch._countleaf = branch._fLeaves[0]._fLeafCount
AttributeError: 'Undefined' object has no attribute '_fLeafCount'
```
This is what it looks like in ROOT:
```cpp
root [0] TFile f("file.root")
(TFile &) Name: file.root Title: 
root [1] tree->Print()
******************************************************************************
*Tree    :tree      :                                                        *
*Entries :        3 : Total =            2839 bytes  File  Size =       1035 *
*        :          : Tree compression factor =   1.00                       *
******************************************************************************
*Br    0 :float_t_branch : float_t_branch/F                                  *
*Entries :        3 : Total  Size=        614 bytes  File Size  =         93 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br    1 :float16_t_branch : float16_t_branch/f                              *
*Entries :        3 : Total  Size=        606 bytes  File Size  =         92 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br    2 :double_t_branch : double_t_branch/D                                *
*Entries :        3 : Total  Size=        639 bytes  File Size  =        106 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br    3 :double32_t_branch : double32_t_branch/d                            *
*Entries :        3 : Total  Size=        615 bytes  File Size  =         96 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
```
I verified that `float16_t_branch` and `double32_t_branch` are each individually sufficient to throw the same `AttributeError` above and removing both results in no error.

**Comment by jpivarski** [comment]
It used to be that these types could only appear inside of a split structure, but now they can be created as top-level branches. I added logic to deal with them as top-level branches in Uproot 4, but not Uproot 3. Did you try that?

**Comment by masonproffitt** [comment]
You mean try this in uproot4? No, I hadn't done that, since this came up while working on tree-writing utilities. I just checked now and uproot4 does seem to be able to read these branches.

**Comment by jpivarski** [comment]
Since this is resolved in Uproot4, I'm going to close it here so that I have a better idea of what's still left to do.
