### ISSUE TITLE
UserWarning: attempted to read missing baskets from incompletely written file, but encountered ValueError: recovered 2 baskets, expected 1

### ISSUE THREAD

**Issue by wiso** [scikit-hep/uproot#60]
I get this warning and a crash just when calling

    open('f.root').get('nllscan').arrays()

file: https://www.dropbox.com/s/1qimjkzz6moppgr/f.root?dl=0

> /afs/cern.ch/user/t/turra/higgs-moriond/venv/lib/python2.7/site-packages/uproot/tree.py:1395: UserWarning: attempted to read missing baskets from incompletely written file, but encountered ValueError: recovered 2 baskets, expected 1
  warnings.warn("attempted to read missing baskets from incompletely written file, but encountered {0}: {1}".format(err.__class__.__name__, str(err)))
Traceback (most recent call last):
  File "analyse_toys_correlation.py", line 13, in <module>
    t.arrays()
  File "/afs/cern.ch/user/t/turra/higgs-moriond/venv/lib/python2.7/site-packages/uproot/tree.py", line 402, in arrays
    futures = [(branch.name, branch.array(interpretation=interpretation, entrystart=entrystart, entrystop=entrystop, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=False)) for branch, interpretation in branches]
  File "/afs/cern.ch/user/t/turra/higgs-moriond/venv/lib/python2.7/site-packages/uproot/tree.py", line 1154, in array
    basket_itemoffset = self._basket_itemoffset(interpretation, basketstart, basketstop, keycache)
  File "/afs/cern.ch/user/t/turra/higgs-moriond/venv/lib/python2.7/site-packages/uproot/tree.py", line 1114, in _basket_itemoffset
    for j, key in enumerate(self._threadsafe_iterate_keys(keycache, True, basketstart, basketstop)):
  File "/afs/cern.ch/user/t/turra/higgs-moriond/venv/lib/python2.7/site-packages/uproot/tree.py", line 834, in _threadsafe_iterate_keys
    key = self._basketkey(keysource, i, complete)
  File "/afs/cern.ch/user/t/turra/higgs-moriond/venv/lib/python2.7/site-packages/uproot/tree.py", line 1400, in _basketkey
    return self._BasketKey(source.parent(), Cursor(self.fBasketSeek[i]), uproot.source.compressed.Compression(self.fCompress), complete)
  File "/afs/cern.ch/user/t/turra/higgs-moriond/venv/lib/python2.7/site-packages/uproot/tree.py", line 1320, in __init__
    raise ValueError("TKey declares that object {0} has {1} bytes but only {2} remain in the file".format(repr(self.fName), self.fNbytes, source.size() - self.fSeekKey))
AttributeError: '_BasketKey' object has no attribute 'fName'

**Comment by jpivarski** [comment]
Thanks, I'll take a look.

**Comment by jpivarski** [comment]
Release [2.8.3](https://github.com/scikit-hep/uproot/releases/tag/2.8.3).
